all: hmmTMB.dll

# See src/Makefile for why every header is a prerequisite, and why TMBad.
HEADERS = hmmTMB.hpp dist.hpp dist_def.hpp added_dists.hpp likelihood.hpp

hmmTMB.dll: hmmTMB.cpp $(HEADERS)
	$(R_HOME)/bin$(R_ARCH_BIN)/Rscript --vanilla -e "invisible(TMB::compile('hmmTMB.cpp', safebounds = FALSE, safeunload = FALSE, framework = Sys.getenv('HMMTMB_AD_FRAMEWORK', 'TMBad')))"
	
clean:
	rm -rf *.dll
